#!/bin/bash

zenity --warning --text="Are you sure you want to delete user?"
user=$(zenity --entry --text="Username" --title="DELETE USER")
sudo userdel -r $user &> /dev/null
zenity --error --text="$user DELETED" --title="USER REMOVED"
