#!/bin/bash

userdet=$(zenity --username --password --title="Login")
user=$(echo $userdet | cut -d"|" -f1)
password=$(echo $userdet | cut -d"|" -f2)
sudo useradd -m $user
echo $password | sudo passwd $user --stdin &> /dev/null
zenity --info --title="User $user created" --text="SUCCESS" 
